# Generated by Django 3.2.4 on 2021-06-13 08:03

from django.db import migrations, models
import django.utils.timezone
import interviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(default=interviews.models.add_an_hour)),
                ('more_info', models.TextField(blank=True, default='', max_length=500)),
                ('interviewee', models.ManyToManyField(related_name='interviewee', to='interviews.Person')),
                ('interviewer', models.ManyToManyField(related_name='interviewer', to='interviews.Person')),
            ],
        ),
    ]
