# Generated by Django 3.2.4 on 2021-06-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.person')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='interviews.roles', to='interviews.Person'),
        ),
    ]
