# Generated by Django 3.2.4 on 2021-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20210613_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='participants',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewee',
            field=models.ManyToManyField(related_name='interviewee', to='interviews.Person'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ManyToManyField(related_name='interviewer', to='interviews.Person'),
        ),
        migrations.DeleteModel(
            name='roles',
        ),
    ]
