# Generated by Django 3.2.4 on 2021-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20210613_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
