# Generated by Django 3.2.4 on 2021-06-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_person_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
